name: tests

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:14-bullseye
        env:
          POSTGRES_DB: highlights_test
          POSTGRES_USER: highlights
          POSTGRES_PASSWORD: test
        ports:
          - 5433:5432

    steps:
      - name: Update sources
        run: sudo apt update --assume-yes

      - name: Install packages
        run: sudo apt install bash gzip postgresql-client tar wget --assume-yes

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create test database schema
        run: |
          PGPASSWORD=test psql \
          --host=127.0.0.1 \
          --port=5433 \
          --username=highlights \
          --dbname=highlights_test \
          --echo-all \
          --quiet \
          --file $GITHUB_WORKSPACE/build/create_schema.sql

      - name: Run tests
        run: make test
